description: NXP PCA9555 GPIO expander

compatible: "nxp,pca9555"

include:
  - name: gpio-controller.yaml
    property-allowlist:
      - gpio-controller
      - "#gpio-cells"

  - name: i2c-device.yaml

properties:
  gpio-controller:
    type: boolean

  "#gpio-cells":
    type: int
    const: 2

  ngpios:
    type: int
    default: 16

  interrupt-gpios:
    type: phandle-array
    required: false
