description: NXP PCA95xx GPIO expander

compatible: "nxp,pca95xx"

include:
  - name: gpio-controller.yaml

properties:
  reg:
    type: int
    required: true

  ngpios:
    type: int
    required: true

  gpio-controller:
    type: boolean
    required: true

  "#gpio-cells":
    type: int
    const: 2
