CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_GPIO_PCA95XX=y

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_GPIO_PCA95XX_INIT_PRIORITY=40
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
